# Generated by Django 2.2.1 on 2019-06-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('answer', models.CharField(default=None, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('type', models.IntegerField(choices=[(0, '--'), (1, 'Bubble'), (2, 'Question'), (3, 'Character'), (4, 'Transition'), (5, 'Button')], default=0)),
                ('position', models.IntegerField(choices=[(0, '--'), (10, 'Top'), (11, 'Top left'), (12, 'Top right'), (20, 'Middle'), (21, 'Middle left'), (22, 'Middle right'), (30, 'Middle top'), (31, 'Middle top left'), (32, 'Middle top right'), (40, 'Middle bottom'), (41, 'Middle bottom left'), (42, 'Middle bottom right'), (50, 'Bottom'), (51, 'Bottom left'), (52, 'Bottom right')], default=0, verbose_name='Position')),
                ('transition', models.IntegerField(choices=[(0, '--'), (1, 'Fade'), (2, 'Slide to left'), (3, 'Slide to right'), (4, 'Slide to top'), (5, 'Slide to bottom')], default=0)),
                ('width', models.IntegerField(choices=[(1, '300'), (2, '400'), (3, '500')], default=0)),
                ('height', models.IntegerField(choices=[(1, '56'), (2, '80'), (3, '100'), (4, '120')], default=0)),
                ('direction', models.IntegerField(choices=[(0, '--'), (1, 'To left'), (2, 'To right'), (3, 'To top'), (4, 'To bottom')], default=0)),
                ('color_type', models.IntegerField(choices=[(0, '--'), (1, 'Background'), (2, 'Text')], default=0)),
                ('color', models.CharField(default=None, max_length=100)),
                ('bubble_type', models.IntegerField(choices=[(0, '--'), (1, 'Top'), (2, 'Bottom'), (3, 'Left'), (4, 'Left top'), (5, 'Left bottom'), (6, 'Right'), (7, 'Right top'), (8, 'Right bottom')], default=0)),
                ('content_name', models.CharField(default=None, max_length=100, verbose_name='Content name')),
                ('content', models.CharField(default='', max_length=2000, verbose_name='Content text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('question', models.CharField(default=None, max_length=500)),
                ('text', models.CharField(default=None, max_length=500)),
                ('order_num', models.IntegerField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Дэлгэцийн нэр')),
                ('background', models.ImageField(default=None, upload_to='static/character', verbose_name='Background Image')),
                ('next_step', models.IntegerField(default=0, verbose_name='Next step')),
                ('prev_step', models.IntegerField(default=0, verbose_name='Prev step')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
