# Generated by Django 2.2.1 on 2019-06-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20190626_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('name', models.CharField(default=None, max_length=250, verbose_name='Түүхийн нэр')),
                ('order_num', models.IntegerField(default=0, verbose_name='Дараалал')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='storystep',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.Story', verbose_name='Түүх'),
        ),
    ]
