# Generated by Django 2.2.1 on 2019-06-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20190626_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storystep',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='story.Story', verbose_name='Түүх'),
            preserve_default=False,
        ),
    ]
