# Generated by Django 2.2.1 on 2019-06-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20190626_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='color_type',
            new_name='bg_color',
        ),
        migrations.AddField(
            model_name='content',
            name='text_color',
            field=models.IntegerField(choices=[(0, '--'), (1, 'Background'), (2, 'Text')], default=0),
        ),
        migrations.AlterField(
            model_name='storystep',
            name='background',
            field=models.ImageField(default=None, upload_to='media/character', verbose_name='Background Image'),
        ),
    ]
