# Generated by Django 2.2.1 on 2019-06-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_content_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='bg_color',
            field=models.CharField(default=None, max_length=10, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/character_image', verbose_name='Character Image'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_color',
            field=models.CharField(default=None, max_length=10, verbose_name='Text Color'),
        ),
    ]
