# Generated by Django 2.2.1 on 2019-06-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_auto_20190627_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='characters',
        ),
    ]
