# Generated by Django 2.2.1 on 2019-06-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_remove_content_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
