# Generated by Django 2.2.1 on 2019-06-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_auto_20190627_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='bg_color',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='content',
            name='position',
            field=models.IntegerField(choices=[(0, '--'), (10, 'Top'), (11, 'Top left'), (12, 'Top right'), (20, 'Middle'), (21, 'Middle left'), (22, 'Middle right'), (30, 'Middle top'), (31, 'Middle top left'), (32, 'Middle top right'), (40, 'Middle bottom'), (41, 'Middle bottom left'), (42, 'Middle bottom right'), (50, 'Bottom'), (51, 'Bottom left'), (52, 'Bottom right'), (60, 'Character 1'), (61, 'Character 2'), (62, 'Character 3'), (63, 'Character 4')], default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_color',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Text Color'),
        ),
    ]
