# Generated by Django 2.2.1 on 2019-07-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_userstory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='step_id',
            new_name='step',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='story_id',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='user_id',
            new_name='user',
        ),
    ]
