# Generated by Django 2.2.1 on 2019-07-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_auto_20190702_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='avatar',
            field=models.ImageField(default=None, upload_to='media/character', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='story',
            name='character_image',
            field=models.ImageField(default=None, upload_to='media/character', verbose_name='Character image'),
        ),
    ]
