# Generated by Django 2.2.1 on 2019-07-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190626_0934'),
        ('story', '0013_auto_20190703_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='character_image',
        ),
        migrations.AddField(
            model_name='story',
            name='character',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Character', verbose_name='Character'),
        ),
    ]
