# Generated by Django 2.2.1 on 2019-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_auto_20190704_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content_image',
            new_name='content_image_l',
        ),
        migrations.AddField(
            model_name='content',
            name='content_image_m',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/character_image', verbose_name='Character Image'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_image_s',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/character_image', verbose_name='Character Image'),
        ),
    ]
