# Generated by Django 2.2.1 on 2019-07-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_auto_20190707_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_image_l',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/character_image', verbose_name='Character Image 3x'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_image_m',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/character_image', verbose_name='Character Image 2x'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_image_s',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/character_image', verbose_name='Character Image 1x'),
        ),
    ]
