# Generated by Django 2.2.1 on 2019-07-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0017_story_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='is_publish',
            field=models.IntegerField(choices=[(0, 'Un publish'), (1, 'Publish')], default=0),
        ),
    ]
