# Generated by Django 2.2.1 on 2019-07-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0018_auto_20190718_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='type',
            field=models.IntegerField(default=0, verbose_name='Log type'),
        ),
    ]
