# Generated by Django 2.2.1 on 2019-07-19 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0021_auto_20190719_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='answer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.Answer'),
        ),
    ]
