# Generated by Django 2.2.1 on 2019-07-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0022_auto_20190719_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='storystep',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='Order num'),
        ),
    ]
