# Generated by Django 2.2.1 on 2019-07-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0023_storystep_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='step',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.StoryStep'),
        ),
    ]
