# Generated by Django 2.2.1 on 2019-06-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lhuser',
            name='dob',
            field=models.IntegerField(default=0, verbose_name='Төрсөн он'),
        ),
    ]
