# Generated by Django 2.2.1 on 2019-06-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190626_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lhuser',
            name='device_id',
            field=models.CharField(default=None, max_length=100, verbose_name='Device id'),
        ),
    ]
