# Generated by Django 2.2.1 on 2019-06-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190626_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lhuser',
            name='device_id',
            field=models.CharField(default='', max_length=100, verbose_name='Device id'),
        ),
    ]
