# Generated by Django 2.2.1 on 2019-06-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190626_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lhuser',
            name='username',
            field=models.CharField(default='', max_length=100, verbose_name='Нэр'),
        ),
    ]
