# Generated by Django 2.2.1 on 2019-07-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190626_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.IntegerField(default=None, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_type',
            field=models.IntegerField(choices=[(0, 'Стрэйт')], default=None, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Эмэгтэй'), (1, 'Эрэгтэй'), (2, 'Аль нь ч биш')], default=None, verbose_name='Gender'),
        ),
    ]
