# Generated by Django 2.2.1 on 2019-07-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190704_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_type',
            field=models.IntegerField(choices=[(0, 'Стрэйт')], default=None, verbose_name='Character type'),
        ),
    ]
