# Generated by Django 2.2.1 on 2019-07-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190705_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(default=None, upload_to='static/character', verbose_name='Character avatar'),
        ),
    ]
