# Generated by Django 2.2.1 on 2019-07-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_character_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='avatar',
        ),
        migrations.AddField(
            model_name='character',
            name='avatar_img',
            field=models.ImageField(default=None, upload_to='static/character/avatar', verbose_name='Character avatar'),
        ),
    ]
