# Generated by Django 2.2.1 on 2019-07-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190706_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='avatar_img',
        ),
        migrations.AddField(
            model_name='character',
            name='avatar_img_l',
            field=models.ImageField(default=None, upload_to='media/character/avatar_l', verbose_name='Character avatar'),
        ),
        migrations.AddField(
            model_name='character',
            name='avatar_img_m',
            field=models.ImageField(default=None, upload_to='media/character/avatar_m', verbose_name='Character avatar'),
        ),
        migrations.AddField(
            model_name='character',
            name='avatar_img_s',
            field=models.ImageField(default=None, upload_to='media/character/avatar_s', verbose_name='Character avatar'),
        ),
        migrations.AlterField(
            model_name='characterimage',
            name='image',
            field=models.ImageField(default=None, upload_to='media/character', verbose_name='Character Image'),
        ),
    ]
