# Generated by Django 2.2.1 on 2019-07-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190707_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterimage',
            name='image',
        ),
        migrations.AddField(
            model_name='characterimage',
            name='image_l',
            field=models.ImageField(default=None, upload_to='media/character', verbose_name='Character Image 3x'),
        ),
        migrations.AddField(
            model_name='characterimage',
            name='image_m',
            field=models.ImageField(default=None, upload_to='media/character', verbose_name='Character Image 2x'),
        ),
        migrations.AddField(
            model_name='characterimage',
            name='image_s',
            field=models.ImageField(default=None, upload_to='media/character', verbose_name='Character Image 1x'),
        ),
    ]
