# Generated by Django 2.2.1 on 2019-07-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190718_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='lhuser',
            name='profile_img',
            field=models.ImageField(default=None, upload_to='media/profile', verbose_name='Profile image'),
        ),
    ]
